{% set name = "numerizer" %}
{% set version = "0.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/numerizer-{{ version }}.tar.gz
  sha256: d15deecd3ad25f1cb89608cb505af1abf31137944a30263d3cdf27c06903c053

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - numerizer
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jaidevd/numerizer
  summary: Python module for converting natural language numbers into ints and floats.
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - thewchan
